name: Build Windows App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install Dependencies
        run: npm install

      - name: Compile Code
        run: |
          npm run build
          copy main.js dist\main.js

      - name: Build Electron Executable
        run: npm run package

      - name: Upload Executable Artifact
        uses: actions/upload-artifact@v4
        with:
          name: proximity-plus
          path: dist-desktop/
